user_login:
  heading: User Login
  attribute: :user_login
template_name:
  heading: Template Name
  attribute: :template_name
  validation:
    options:
      type: :list
      formula1: "$A$1:$A$2"
      allowBlank: false
      showInputMessage: true
      showErrorMessage: true
      errorStyle: :stop
      errorTitle: "Submission template"
      error: "You must enter a Submission template from the list provided."
      promptTitle: "Submission template"
      prompt: "Provide a Submission template from the approved list"
    range_name: :submission_template
  conditional_formattings:
    empty_cell:
    is_error:
project_name:
  heading: Project Name
  attribute: :project_name
study_name:
  heading: Study Name
  attribute: :study_name
submission_name:
  heading: Submission name
  attribute: :submission_name
barcode:
  heading: Barcode
  attribute: :barcode
plate_well:
  heading: Plate Well
  attribute: :plate_well
asset_group_name:
  heading: Asset Group Name
fragment_size_from:
  heading: Fragment Size From
  attribute: :fragment_size_from
  unlocked: true
  validation:
    options:
      type: :whole
      operator: :greaterThanOrEqual
      formula1: "1"
      allowBlank: false
      showInputMessage: true
      promptTitle: "Insert size from"
      prompt: "The minimum insert size in the library"
  conditional_formattings:
    empty_cell:
    number_greater_than_one:
    is_text:
fragment_size_to:
  heading: Fragment Size To
  attribute: :fragment_size_to
  unlocked: true
  validation:
    options:
      type: :whole
      operator: :greaterThanOrEqual
      formula1: "1"
      allowBlank: false
      showInputMessage: true
      promptTitle: "Insert size to"
      prompt: "Maximum insert size in the library"
      showErrorMessage: true
      errorStyle: :stop
      errorTitle: "Insert size to"
      error: "Insert size to must be a whole number, greater or equal to the insert size from"
  conditional_formattings:
    empty_cell:
    number_greater_than_one:
    is_text:
pcr_cycles:
  heading: PCR Cycles
library_type:
  heading: Library Type
  unlocked: true
  validation:
    options:
      type: :list
      formula1: "$A$1:$A$2"
      allowBlank: false
      showInputMessage: true
      showErrorMessage: true
      errorStyle: :stop
      errorTitle: "Library type"
      error: "You must enter a Library type from the list provided."
      promptTitle: "Library type"
      prompt: "Provide a library type from the approved list"
    range_name: :library_type
  conditional_formattings:
    empty_cell:
    is_error:
bait_library:
  heading: Bait Library Name
  unlocked: true
  validation:
    options:
      type: :list
      formula1: "$A$1:$A$2"
      allowBlank: false
      showInputMessage: true
      showErrorMessage: true
      errorStyle: :stop
      errorTitle: "Bait library"
      error: "You must enter a Bait library from the list provided."
      promptTitle: "Bait library"
      prompt: "Provide a Bait library from the approved list"
    range_name: :bait_library
  conditional_formattings:
    empty_cell:
    is_error:
read_length:
  heading: Read Length
number_of_lanes:
  heading: Number of lanes
comments:
  heading: Comments
pre_capture_plex_level:
  heading: Pre-capture Plex Level
pre_capture_group:
  heading: Pre-capture Group
priority:
  heading: Priority
primer_panel:
  heading: Primer Panel
  unlocked: true
  validation:
    options:
      type: :list
      formula1: "$A$1:$A$2"
      allowBlank: false
      showInputMessage: true
      showErrorMessage: true
      errorStyle: :stop
      errorTitle: "Primer Panel"
      error: "You must enter a Primer panel from the list provided."
      promptTitle: "Primer panel"
      prompt: "Provide a primer panel from the approved list"
    range_name: :primer_panel
  conditional_formattings:
    empty_cell:
    is_error:
gigabases_expected:
  heading: Gigabases Expected
