language: ruby
rvm:
  - jruby-9.1.2.0
sudo: false
cache: bundler
bundler_args: --without warehouse development deployment
env: "CUCUMBER_FORMAT=progress"
before_install:
  - export TZ=Europe/London
before_script:
  - "RAILS_ENV=test bundle exec rake db:create"
  - "bundle exec rake db:test:load"
  - "RAILS_ENV=test bundle exec rake db:seed"
script:
  - "bundle exec rake test"
  - "bundle exec cucumber -r features"
