language: ruby
# We don't specify a list of ruby versions, as Travis will fall back to .ruby-version
dist: xenial
sudo: required
services: mysql
addons:
  apt:
    packages:
    - haveged
    - google-chrome-stable
    - chromium-chromedriver
cache:
  bundler: true
bundler_args: "--without warehouse deployment"
env:
  global:
  - TZ=Europe/London
  - CUCUMBER_FORMAT=DebugFormatter
  - PATH=$PATH:/usr/lib/chromium-browser/
  - DISPLAY=:99.0
before_install:
- mv config/aker.yml.example config/aker.yml
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rubocop
jobs:
  include:
  - stage: build
    if: tag IS present
    script: "./compile-build"
    name: Compile Build
    deploy:
      provider: releases
      file: release.tar.gz
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
        repo: sanger/sequencescape
      api_key:
        secure: eWwbjG2LpK3cTHbqJfccIpcNj0PUl2YqGRYVAOQX+YPUtjOjnR4hqDMIUJTCVAHQ8PUC3yh/H7Sf4F7I5DQ5SdhY2Yeiusucig3V8yUdO6oHrpgaN2r9Nd/nM/vRxL7oVCI84Ahhu5mKL3x1PayTTpRjiu1KqL/BMbV//6s5jBs=
