language: ruby
rvm:
  - jruby-9.1.6.0
  - 2.3.1
sudo: false
cache: bundler
bundler_args: --without warehouse deployment
env:
  - "TZ=Europe/London SUITE='rake test' RUBYOPT='-W0'" # RUBYOPT disables warnings turned on by default in rake 11. See note in README
  - "JRUBY_OPTS='' CUCUMBER_FORMAT=progress TZ=Europe/London SUITE='cucumber'"
  - "SUITE=rubocop"
before_script:
  - "RAILS_ENV=test bundle exec rake db:setup"
script:
  - "bundle exec $SUITE"
matrix:
  allow_failures:
  - rvm: 2.3.1
