language: ruby
rvm:
  - jruby-9.1.5.0
sudo: false
cache: bundler
bundler_args: --without warehouse development deployment
env:
  - "CUCUMBER_FORMAT=progress TZ=Europe/London SUITE='rake test'"
  - "JRUBY_OPTS='' CUCUMBER_FORMAT=progress TZ=Europe/London SUITE='cucumber'"
before_script:
  - "RAILS_ENV=test bundle exec rake db:setup"
script:
  - "bundle exec $SUITE"
