---
- app/controllers/admin/users_controller.rb
- app/controllers/admin/projects_controller.rb
- app/controllers/assets/comments_controller.rb
- app/controllers/assets_controller.rb
- app/controllers/batches_controller.rb
- app/controllers/locations_controller.rb
- app/controllers/receptions_controller.rb
- app/controllers/request_information_types_controller.rb
- app/controllers/requests/comments_controller.rb
- app/controllers/samples/comments_controller.rb
- app/controllers/samples_controller.rb
- app/controllers/studies/comments_controller.rb
- app/controllers/studies_controller.rb
- app/controllers/barcode_printers_controller.rb
- app/models/map.rb
- app/views/activities/edit.html.erb
- app/views/activities/new.html.erb
- app/views/admin/property_definitions/index.html.erb
- app/views/assets/comments/_comment.html.erb
- app/views/assets/comments/_list.html.erb
- app/views/assets/new_request.html.erb
- app/views/implements/new.html.erb
- app/views/locations/edit.html.erb
- app/views/locations/new.html.erb
- app/views/pipelines/_manual_qc_batches.html.erb
- app/views/pipelines/_qc_batches.html.erb
- app/views/request_information_types/edit.html.erb
- app/views/request_information_types/new.html.erb
- app/views/requests/comments/_comment.html.erb
- app/views/requests/comments/_list.html.erb
- app/views/robot_properties/edit.html.erb
- app/views/robot_properties/new.html.erb
- app/views/robots/edit.html.erb
- app/views/robots/new.html.erb
- app/views/samples/comments/_comment.html.erb
- app/views/samples/comments/_list.html.erb
- app/views/studies/comments/_comment.html.erb
- app/views/studies/comments/_list.html.erb
- app/views/studies/workflows/_asset_progress.html.erb
- app/views/studies/workflows/_sample_progress.html.erb
- app/views/studies/workflows/_study_summary.html.erb
- app/views/studies/workflows/_summary.html.erb
- app/views/studies/workflows/_summary_for_request_type.html.erb
- app/views/tags/edit.html.erb
- app/views/tags/new.html.erb
- app/views/tasks/new.html.erb
- app/views/workflows/_descriptor.html.erb
- app/views/workflows/_dna_qc_batches.html.erb
- app/views/workflows/_manual_qc_batches.html.erb
- app/views/workflows/_qc_results.html.erb
- app/views/workflows/auto_batch.html.erb
